# -*- coding: utf-8 -*-
"""Assignment4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qVwyeSmtJ1-o25fWcR2b21xTCmjjyUO6
"""

import numpy as np
import matplotlib.pyplot as plt
from sympy import *
a, b, c = symbols('a b c')
# given triangle vertices
A=[a,b+c]
B=[b,c+a]
C=[c,a+b]

area=((A[0]*(B[1]-C[1]))+(B[0]*(C[1]-A[1])+(C[0]*(A[1]-B[1]))))
print("Traditional Method")
print("Area of the triangle is :", area)

#Triangle vertices
A = np.array([a,b+c]) 
B = np.array([b,c+a]) 
C = np.array([c,a+b]) 
D = np.vstack((A-B,A-C))
Ar = abs((D[0][0]*D[1][1]-D[0][1]*D[1][0])/2)

print("Matrices Method")
print("Area of the triangle is :",round(Ar/2))
if(Ar == 0):
  print("Since the area is ", Ar, "the given points form a straight line.")
else:
  print("Since the area is ", Ar, "the given points form a Triangle.")